- hosts: central_monitoring_servers
  become: true
  vars_files:
    - vars/default.yml
  tasks:

    - name: Ensure Prometheus config directory exists
      file: path=/var/prometheus state=directory

    - name: Copy Prometheus config files
      copy:
        src: "{{ prometheus_config }}"
        dest: /var/prometheus

    - name: Create the docker network
      community.docker.docker_network:
        name: monitoring_net

    - name: Run Prometheus Timeseries Database
      community.docker.docker_container:
        name: prometheus
        image: prom/prometheus:latest
        command: --config.file=/etc/prometheus/prometheus.yml --web.enable-lifecycle
        state: started
        ports:
          - "9090:9090"
        volumes:
          - /var/prometheus:/etc/prometheus
          - prometheus-data:/prometheus
        restart_policy: unless-stopped
        networks:
          - name: monitoring_net

    - name: Run Grafana Dashboard
      community.docker.docker_container:
        name: grafana
        image: grafana/grafana-oss:latest
        state: started
        ports:
          - "3000:3000"
        volumes:
          - grafana-data:/var/lib/grafana
        restart_policy: unless-stopped
        networks:
          - name: monitoring_net
