- hosts: central_monitoring_servers
  become: true
  vars_files:
    - vars/default.yml
  tasks:
    - name: Create/restart Node exporter container
      community.docker.docker_container:
        name: node-exporter
        image: quay.io/prometheus/node-exporter:latest
        command: --path.rootfs=/host
        pid_mode: host
        state: started
        recreate: yes
        volumes:
          - /:/host:ro,rslave
        networks:
          - name: monitoring_net                                    